steps = [
    step("INSERT INTO ming (name) VALUES "
         "('water'), "
         "('salt'), "
         "('what flour (type 450)'), "
         "('what flour (type 500)'), "
         "('what flour (type 550)'), "
         "('what flour (type 750)'), "
         "('what flour (type 1850)'), "
         "('rye flour (type 720)'), "
         "('rye flour (type 2000)'), "
         "('yeast fresh'), "
         "('dried yeast'),"
         "('bread sourdough'), "
         "('sugar'), "
         "('rice'), "
         "('raisins'), "
         "('cranberries'), "
         "('lemon'), "
         "('mint'), "
         "('savory'), "
         "('sage'), "
         "('juniper fruit'), "
         "('allspice'), "
         "('star anise'), "
         "('carnations'), "
         "('black pepper'), "
         "('anise seeds'), "
         "('tarragon'), "
         "('cloendra'), "
         "('cardamom'), "
         "('cinnamon sticks'), "
         "('nutmeg'), "
         "('turmeric'), "
         "('rosemary'), "
         "('oregano'), "
         "('bay leaf'), "
         "('vanilla pod'); ")
]

